### ISSUE TITLE
authentication failed

### ISSUE THREAD

**Issue by nikita-skobov** [esrlabs/josh#128]
Hi, Im trying to run the example on the README, and I saw that when I tried to clone, git is asking me for authentication. I looked at the source code and I saw there were passwords being set via an environment variable, so I tried running the server again by giving an explicit user/pass:

```
JOSH_USERNAME="josh" JOSH_PASSWORD="josh" ./target/release/josh-proxy --local ./tmp1/ --remote=https://github.com --port=8000
```

but when I tried:
```
git clone http://localhost:8000/git/git.git:/Documentation.git
```

I still got:

```
Cloning into 'Documentation'...
Username for 'http://localhost:8000': josh
Password for 'http://josh@localhost:8000': 
fatal: Authentication failed for 'http://localhost:8000/git/git.git:/Documentation.git/'
```

What is the right way to authenticate?

**Comment by initcrash** [comment]
Hi Nikita,
You are raising a good point here 👍 
We never used the proxy without authentication so it will always require credentials even if the upstream host does not
require them itself. I consider this a bug and will fix it.

Anyway the credentials you need to provide are the same as those you would provide for the upstream. So in this case your github http username and password.

The environment variables JOSH_USERNAME and JOSH_PROXY are not used for configuration but as a means to pass on those values down to it's own grandchild process:
josh-proxy sets them, calls git-http-backend which in turn calls an update-hook that reads the variables.

**Comment by nikita-skobov** [comment]
Hey thanks for the quick response, just wondering about this:

> Anyway the credentials you need to provide are the same as those you would provide for the upstream. So in this case your github http username and password.

Is that necessary for it to work? I thought since the github repository is public that I should be able to clone without providing my user/pass

**Comment by initcrash** [comment]
No it should not be necessary. It's a bug. I never noticed it because in our production deployment there are no repos with public access.
