### ISSUE TITLE
Trailing slash at end of map folder in workspace.josh returns 502

### ISSUE THREAD

**Issue by LMG** [esrlabs/josh#145]
Starting with a mapping like so in workspace.josh:
```
parent/foo = :/folder/parent/foo
parent/foo = :/folder/parent/bar
```
replacing it with 
```
parent/ = :/folder/parent
```
returns error 502 when the commit is pushed from the workspace

**Comment by LMG** [comment]
https://github.com/LMG/josh/tree/fix_workspace_change_parent demonstrates the bug with a new cram test

**Comment by LMG** [comment]
The error is actually linked to the slash at the end of `parent/`. 
The crash is still not very helpful.

**Comment by initcrash** [comment]
fixed
