### ISSUE TITLE
Unused label

### ISSUE THREAD

**Issue by BartMassey** [esrlabs/josh#17]
I'm hoping to turn the `unused_labels` lint to `warn` on nightly shortly. A Crater run found that you have `warnings` set to `deny` and an unused label `'walk` in your source: https://crater-reports.s3.amazonaws.com/pr-66325/try%239007306dd8a80184ce3cb60cdbee0f3b81083ccd/gh/esrlabs.centralgithook/log.txt

If you could remove this label or change it to `'_walk` or set `unused_labels` to `allow` it will avoid breakage. Thanks!

**Comment by hellow554** [comment]
For context see https://github.com/rust-lang/rust/pull/66325

**Comment by initcrash** [comment]
Fixed in cbf88912e3416a91dbd0bdaabc9869670dd8ade5
