### ISSUE TITLE
Add automic doc building and deployment of josh docs to github workflow(s)

### ISSUE THREAD

**Issue by Nicoretti** [esrlabs/josh#233]
It looks like that the render docs on [https://esrlabs.github.io./josh](https://esrlabs.github.io./josh ) do not match exactly match the latest documentation within the repository. By automating the deployment this should not be an issue in the future anymore

**Comment by LMG** [comment]
Solved :heavy_check_mark:

**Comment by LMG** [comment]
Not solved :x:

**Comment by LMG** [comment]
Should work now, can you confirm ?
