### ISSUE TITLE
JOSH returns 500 on `git ls-remote` when there is no master branch

### ISSUE THREAD

**Issue by jonatansberg** [esrlabs/josh#238]
Hey!

We're successfully using JOSH to virtualise our main trunk repo so that we can consume libraries in other downstream projects. This works great for the most part. We have however run in to an issue when using JOSH together with `git-subrepo` and a renamed master branch in the source repo. 

As a workaround we have been adding the branch name to the filter section of the remote url, effectively turning it in to the master branch, but this seems to cause issues with pushing changes back upstream. 

Cloning a virtualised repo directly works just fine, even when there is no master branch. The correct default brach is identified anyways. The same way, adding that full source repo using `git-subrepo`, everything works and the correct default brach is identified. 

The problem seems to arise when using all three things at once, and it seems to come down to JOSH returning a 500 error on the `ls-remote` request initiated by `git-subrepo`. 

Going through the logs it seems like the following fetch call is the culprit:
```
git fetch --no-tags https://jonatansberg@github.com/<repo/name>.git \'+refs/heads/*:refs/josh/upstream/<name>.git/refs/heads/*\' \'+refs/tags/*:refs/josh/upstream/<name>.git/refs/tags/*\' \'+refs/heads/master:refs/josh/upstream/<name>.git/refs/heads/master\'" "/data/git/" 
```

Since it fails with the following:
```
fatal: Couldn't find remote ref refs/heads/master
```

Adding `@main` to the remote url for the virtual repo sets the correct `headref` and makes the whole thing work as expected. However even though cloning and pulling new changes from the remote works as expected, my colleagues have reported that they have been unable to push new changes back upstream. 

If this is expected to work with a branch name specified like that, we could investigate the cause of the error pushing upstream further.

**Comment by initcrash** [comment]
Hey,
Yes that is definitely a bug. We will fix it.
What version of josh are you using?

**Comment by jonatansberg** [comment]
I believe we're on bab49919d550c5adda4d19841497eb657d7f138a, but I'm not 100% sure.

**Comment by initcrash** [comment]
So, I looked into the history. This has been fixed for some time already: fa29dc8eccfbe07f65f7b7cd76f7c8bfcc059bf6

**Comment by jonatansberg** [comment]
Thats great! I skimmed through the history before opening this issue, but I must have missed that commit somehow. 

I'm pushing a new build to our server, hopefully that should resolve everything.

**Comment by jonatansberg** [comment]
The automatic head branch detection still seems to fail for some reason, but using `git-subrepo` with the branch flag seems to work just fine! 

There are still some issues pushing code back upstream, but I think they might relate to `git-subrepo` rather than JOSH. 

Thanks again fot your help!
