### ISSUE TITLE
Support token based authentication

### ISSUE THREAD

**Issue by christian-schilling** [esrlabs/josh#246]
Github announced that they will deprecate credential based auth in August.
To keep josh usable with github we need to implement a supported alternative.

**Comment by LMG** [comment]
From what I understand, this seems to be a server side change, which should not affect the client (and thus the proxy).

https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token 

```
Using a token on the command line

Once you have a token, you can enter it instead of your password when performing Git operations over HTTPS.

For example, on the command line you would enter the following:

    $ git clone https://github.com/username/repo.git
    Username: your_username
    Password: your_token
```

**Comment by LMG** [comment]
See also: 

https://docs.github.com/en/github/authenticating-to-github/about-authentication-to-github

```
You can work with all repositories on GitHub over HTTPS, even if you are behind a firewall or proxy. Every time you use Git to authenticate with GitHub, you'll be prompted to enter your credentials to authenticate with GitHub, unless you cache them with a credential helper. When Git prompts you for your password, enter your personal access token (PAT) instead. Password-based authentication for Git is deprecated, and using a PAT is more secure. For more information, see "Creating a personal access token."
```

**Comment by jstriebel** [comment]
Just tested this with GitHub using a Personal Access Token (PAT) for a private repository, works as expected. (However, ssh support would be awesome #22  :+1:)

**Comment by christian-schilling** [comment]
Thanks @jstriebel for trying this out and letting us know.

#22 Is not really doable with josh-proxy, but we are thinking about a standalone version that will also include ssh support.

**Comment by christian-schilling** [comment]
Nothing to fix.
