### ISSUE TITLE
If directories/files are moved within the monorepo (rename/move) will leave workspaces with no files (Empty Mapping)

### ISSUE THREAD

**Issue by Nicoretti** [esrlabs/josh#299]
When somebody is moving/renaming a directory or file within the monorepo, the reference within workspaces (`workspace.json`)
can be invalidated (resulting in an empty path). Therefore the user will end up with an unexpected not fully populated workspace.

There should be at least some sort of warning on push/fetch so the user is informed about the potentional issue.

**Comment by christian-schilling** [comment]
This is not a josh issue: It comes down to a change (in this case move/rename) in the monorepo affecting a workspace. The change is correctly reflected (files are not there anymore).
If such a change is valid is up to CI/CD to decide.

**Comment by LMG** [comment]
#328 should help with this, the next push will notify the user with a warning that the paths don't map to anything in the source repo
