### ISSUE TITLE
Add FAQ to josh documentation

### ISSUE THREAD

**Issue by Nicoretti** [esrlabs/josh#417]
First items could be:

* How is josh different from partial clone and sparse checkout ...
 (possible answer: https://github.com/esrlabs/josh/issues/23#issuecomment-880875575)
 
 * Also we might address the most prominent questions which came up on Hacker News
  (https://news.ycombinator.com/item?id=27844363)

**Comment by LMG** [comment]
First version here: https://github.com/esrlabs/josh/pull/420
