### ISSUE TITLE
Silent error on missing graphql key in hbs 

### ISSUE THREAD

**Issue by LMG** [esrlabs/josh#431]
when an .hbs file contains a reference to a non-existent entry in graphql result, no error is produced: the reference is silently replaced with an empty string

**Comment by christian-schilling** [comment]
Look simple to catch the error: https://docs.rs/handlebars/4.1.1/handlebars/struct.Handlebars.html#method.set_strict_mode
The question is though how and where to report it.

**Comment by resetnow** [comment]
HTTP 422 seems appropriate, or perhaps 500 with a message

**Comment by christian-schilling** [comment]
I don't think 400 is correct in this case: The request is legal, the error is caused by something that is stored on the server side.
422 seems more fitting.

**Comment by LMG** [comment]
Ok, you're right, I wasn't considering it's something stored on the server already. Updating it.
